on:
  workflow_dispatch:
    inputs:
      messageIds:
        description: "Which message ids should it be?"
        required: false
        default: "b077588c-488f-458c-bf5a-33585850c3ae,dcd83c57-aa47-45a2-b41d-0bd8d3f95724"
name: Render video
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies (ffmpeg and fonts)
        run: |
          sudo apt-get update -yqq
          sudo apt-get install -yq --no-install-recommends \
            ffmpeg \
            fonts-noto-core fonts-noto-cjk fonts-noto-color-emoji fonts-noto-mono
      - name: Render video
        run: npm run build -- --props="./input-props.json"
        env:
          REMOTION_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload video
        uses: actions/upload-artifact@v3
        with:
          name: out.mp4
          path: out.mp4
